package cl.preguntame.model;
// Generated 15-01-2016 08:04:00 PM by Hibernate Tools 3.6.0



/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String correo;
     private String mensaje;

    public Contacto() {
    }

    public Contacto(String nombre, String correo, String mensaje) {
       this.nombre = nombre;
       this.correo = correo;
       this.mensaje = mensaje;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }




}


