package cl.preguntame.model;
// Generated 15-01-2016 08:04:00 PM by Hibernate Tools 3.6.0



/**
 * DatosEmpresa generated by hbm2java
 */
public class DatosEmpresa  implements java.io.Serializable {


     private String nombre;
     private String descripcion;
     private String representante;
     private String direccion;
     private String telefono;

    public DatosEmpresa() {
    }

    public DatosEmpresa(String nombre, String descripcion, String representante, String direccion, String telefono) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.representante = representante;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(String representante) {
        this.representante = representante;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


