package cl.preguntame.model;
// Generated 04-dic-2016 21:04:10 by Hibernate Tools 3.6.0



/**
 * Relacion generated by hbm2java
 */
public class Relacion  implements java.io.Serializable {


     private Integer id;
     private TipoRelacion tipoRelacion;
     private Concepto conceptoByConcepto1;
     private Concepto conceptoByConcepto2;

    public Relacion() {
    }

    public Relacion(TipoRelacion tipoRelacion, Concepto conceptoByConcepto1, Concepto conceptoByConcepto2) {
       this.tipoRelacion = tipoRelacion;
       this.conceptoByConcepto1 = conceptoByConcepto1;
       this.conceptoByConcepto2 = conceptoByConcepto2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipoRelacion getTipoRelacion() {
        return this.tipoRelacion;
    }
    
    public void setTipoRelacion(TipoRelacion tipoRelacion) {
        this.tipoRelacion = tipoRelacion;
    }
    public Concepto getConceptoByConcepto1() {
        return this.conceptoByConcepto1;
    }
    
    public void setConceptoByConcepto1(Concepto conceptoByConcepto1) {
        this.conceptoByConcepto1 = conceptoByConcepto1;
    }
    public Concepto getConceptoByConcepto2() {
        return this.conceptoByConcepto2;
    }
    
    public void setConceptoByConcepto2(Concepto conceptoByConcepto2) {
        this.conceptoByConcepto2 = conceptoByConcepto2;
    }




}


