package cl.preguntame.model;
// Generated 04-dic-2016 21:04:10 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoRelacion generated by hbm2java
 */
public class TipoRelacion  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set relacions = new HashSet(0);

    public TipoRelacion() {
    }

	
    public TipoRelacion(String nombre) {
        this.nombre = nombre;
    }
    public TipoRelacion(String nombre, Set relacions) {
       this.nombre = nombre;
       this.relacions = relacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRelacions() {
        return this.relacions;
    }
    
    public void setRelacions(Set relacions) {
        this.relacions = relacions;
    }




}


